### ISSUE TITLE
Error with API call - 10426

### ISSUE THREAD

**Issue by dabcorp** [kreative/F3-PYPL#8]
Hello,

Demo not work, error Error with API call - 10426.

Same error in my apps :

```
$paypal = new PayPal;
$paypal->setLineItem("Phone Case", 1, "10.00");
$optional=array('ADDROVERRIDE'=>1);
$result = $paypal->create("Sale", "EUR", "10.00");
```

Log :

`Transaction refused because of an invalid argument. See additional error messages for details.&L_LONGMESSAGE0=Item total is invalid.&L_SEVERITYCODE0=Error`

**Comment by dabcorp** [comment]
I change this ligne "176" in PayPal.php and its work :

```
            //$this->lineitems["PAYMENTREQUEST_0_ITEMAMT"] = sprintf('%0,2f', $this->itemtotal);	
		$this->lineitems["PAYMENTREQUEST_0_ITEMAMT"] = $this->itemtotal;	
```

**Comment by kreative** [comment]
Hey,

I've ran your code but I was unable to replicate the error.

$paypal = new PayPal;
$paypal->setLineItem("Phone Case", 1, "10.00");
$optional=array('ADDROVERRIDE'=>1);
$result = $paypal->create("Sale", "EUR", "10.00");

Sat, 15 Apr 2017 14:00:29 +0200 [::1] Request: USER=*****&PWD=*****&SIGNATURE=*****&VERSION=204&RETURNURL=http://localhost/f3pypl&CANCELURL=http://localhost/f3pypl&PAYMENTREQUEST_0_PAYMENTACTION=Sale&PAYMENTREQUEST_0_CURRENCYCODE=EUR&PAYMENTREQUEST_0_AMT=10.00&L_PAYMENTREQUEST_0_NAME0=Phone 

Can you enable log=1 in the config and paste the resulting request?

**Comment by dabcorp** [comment]
```
Sat, 15 Apr 2017 12:52:15 +0000 [::1] Request: USER=xxxxx&PWD=*****&SIGNATURE=*****&VERSION=204&RETURNURL=http://localhost/paypal_process&CANCELURL=http://localhost/paypayl_cancel&PAYMENTREQUEST_0_PAYMENTACTION=Sale&PAYMENTREQUEST_0_CURRENCYCODE=EUR&PAYMENTREQUEST_0_AMT=165&PAYMENTREQUEST_0_SHIPPINGAMT=15&L_PAYMENTREQUEST_0_NAME0=1&L_PAYMENTREQUEST_0_QTY0=1&L_PAYMENTREQUEST_0_AMT0=150.00&PAYMENTREQUEST_0_ITEMAMT=2f&BRANDNAME=TARAPRINT&METHOD=SetExpressCheckout
Sat, 15 Apr 2017 12:52:15 +0000 [::1] Response: TIMESTAMP=2017-04-15T12:52:12Z&CORRELATIONID=b63d7900eb5f1&ACK=Failure&VERSION=204&BUILD=32305669&L_ERRORCODE0=10426&L_ERRORCODE1=10413&L_SHORTMESSAGE0=Transaction refused because of an invalid argument. See additional error messages for details.&L_SHORTMESSAGE1=Transaction refused because of an invalid argument. See additional error messages for details.&L_LONGMESSAGE0=Item total is invalid.&L_LONGMESSAGE1=The totals of the cart item amounts do not match order amounts.&L_SEVERITYCODE0=Error&L_SEVERITYCODE1=Error
```

**Comment by kreative** [comment]
> &PAYMENTREQUEST_0_ITEMAMT=2f

Well in this case it looks like sprintf isn't working. Looking at the code you commented out above you've changed the function and changed a period to a comma.

`sprintf('%0,2f', $this->itemtotal); `

should read

`sprintf('%0.2f', $this->itemtotal);`

Can you check that and try again? Thanks

**Comment by dabcorp** [comment]
Sat, 15 Apr 2017 13:42:14 +0000 [::1] Request: USER=xxxxx&PWD=*****&SIGNATURE=*****&VERSION=204&RETURNURL=http://localhost/paypal_process&CANCELURL=http://localhost/paypayl_cancel&PAYMENTREQUEST_0_PAYMENTACTION=Sale&PAYMENTREQUEST_0_CURRENCYCODE=EUR&PAYMENTREQUEST_0_AMT=165&PAYMENTREQUEST_0_SHIPTONAME=xxx&PAYMENTREQUEST_0_SHIPTOSTREET=8xxx&PAYMENTREQUEST_0_SHIPTOSTREET2=&PAYMENTREQUEST_0_SHIPTOCITY=Lyon&PAYMENTREQUEST_0_SHIPTOSTATE=xxx&PAYMENTREQUEST_0_SHIPTOZIP=xxxx&PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE=FR&PAYMENTREQUEST_0_SHIPPINGAMT=15&L_PAYMENTREQUEST_0_NAME0=1&L_PAYMENTREQUEST_0_QTY0=1&L_PAYMENTREQUEST_0_AMT0=150.00&PAYMENTREQUEST_0_ITEMAMT=150,00&DESC=11&METHOD=SetExpressCheckout
Sat, 15 Apr 2017 13:42:14 +0000 [::1] Response: TIMESTAMP=2017-04-15T13:42:11Z&CORRELATIONID=960593b62039&ACK=Failure&VERSION=204&BUILD=32305669&L_ERRORCODE0=10426&L_ERRORCODE1=10413&L_SHORTMESSAGE0=Transaction refused because of an invalid argument. See additional error messages for details.&L_SHORTMESSAGE1=Transaction refused because of an invalid argument. See additional error messages for details.&L_LONGMESSAGE0=Item total is invalid.&L_LONGMESSAGE1=The totals of the cart item amounts do not match order amounts.&L_SEVERITYCODE0=Error&L_SEVERITYCODE1=Error

**Comment by kreative** [comment]
&PAYMENTREQUEST_0_ITEMAMT=150,00 <- another comma. It might be easier to just restore the original lib file :)

**Comment by kreative** [comment]
Hi dabcorp did you get the issue resolved?
