### ISSUE TITLE
namespace ?

### ISSUE THREAD

**Issue by daslicht** [kreative/F3-PYPL#9]
Hi,
which namespace to use when using it by loading it with composer please?

I tried something like:
```
use kreative\f3-pypl\Paypal;
```
but that - is not allowed

**Comment by kreative** [comment]
Are you using autoload? You shouldn't need to define the namespace? (yes in hindsight f3-pypl was a poor choice in naming convention!)

**Comment by daslicht** [comment]
I use both autoload and composer :) I just loaded it now via f3 autoload. Thank you !
